--DB init

-- ?òÑ ?îÑÎ°úÏ†ù?ä∏?óê?Ñú ?ïÑ?öî?ïú 
-- DROP TABLE , SEQUENCE ,  CREATE TABLE, CTRATE SEQUENCE
-- DUMMY DATA INSERT 
DROP TABLE ADMIN;
DROP TABLE NOTICE;
DROP TABLE MEMBERGRADE;
DROP TABLE MEMBER;


CREATE TABLE ADMIN(
AdminId VARCHAR2(30) PRIMARY KEY,
AdminPw VARCHAR2(30) NOT NULL
);

SELECT *FROM ADMIN;

COMMIT;

CREATE TABLE NOTICE(
NoticeNo NUMBER(10) PRIMARY KEY,
NoticeTitle VARCHAR2(300) NOT NULL,
NoticeContent VARCHAR2(1000),
NoticeFile VARCHAR2(300),
NoticeReadCount NUMBER(10) DEFAULT 0 NOT NULL,
NoticeDate DATE DEFAULT SYSDATE
);

SELECT * FROM NOTICE;

CREATE TABLE MEMBERGRADE(
MemberGradeNo VARCHAR2(20) DEFAULT '0' PRIMARY KEY,
MemberGradeName VARCHAR2(20) NOT NULL
);

COMMIT;

SELECT * FROM MEMBERGRADE;

COMMIT;

CREATE TABLE MEMBER(
MemberId VARCHAR2(30) PRIMARY KEY,
MemberPw VARCHAR2(30) NOT NULL,
MemberName VARCHAR2(30) NOT NULL,
MemberBirth DATE NOT NULL,
MemberPhone VARCHAR2(30) NOT NULL,
MemberEmail VARCHAR2(100) NOT NULL,
MemberAddress VARCHAR2(255) NOT NULL,
MemberPoint NUMBER(8) DEFAULT 0 NOT NULL,
MemberGradeNo VARCHAR2(20) DEFAULT 0 REFERENCES MEMBERGRADE(MemberGradeNo),
MemberAmount NUMBER(10) DEFAULT 0 NOT NULL,
MemberState NUMBER(1) DEFAULT 0 NOT NULL
);

DROP SEQUENCE NOTICESEQUENCE;
CREATE SEQUENCE NOTICESEQUENCE MAXVALUE 999999 NOCACHE NOCYCLE;

SELECT * FROM MEMBER;

COMMIT;

INSERT INTO MEMBERGRADE(MemberGradeNo, MemberGradeName) VALUES('0', 'NORMAL');
INSERT INTO MEMBERGRADE(MemberGradeNo, MemberGradeName) VALUES('1', 'VIP');
SELECT * FROM membergrade;

INSERT INTO ADMIN(adminid, AdminPw) VALUES('admin', 'admin');

SELECT * FROM admin;

INSERT INTO MEMBER(MemberId, MemberPw, MemberName, MemberBirth, MemberPhone, MemberEmail, MemberAddress)
  VALUES('AAA', 'AAA', 'AAA', TO_DATE('941201', 'YYMMDD'), '01075596366', 'AAA@AAA', '§±§±§±Ω√'); 

SELECT * FROM MEMBER;

INSERT INTO NOTICE(NoticeNo, NoticeTitle, NoticeContent)
  VALUES(NOTICESEQUENCE.NEXTVAL, 'AAA', 'AAAAA');
  
SELECT * FROM NOTICE;



CREATE TABLE QNA(
QNANO NUMBER(10) PRIMARY KEY,
QNATITLE VARCHAR2(30) NOT NULL,
QNACONTENT CLOB NOT NULL,
QNAFILE VARCHAR2(200) ,
QNAHIT NUMBER(6)DEFAULT 0 ,
QNADATE DATE NOT NULL,
QNAIP VARCHAR2(200) ,
QNANOPW VARCHAR2(20),
QNAGROUP NUMBER(3) NOT NULL,
QNASTEP NUMBER(3) DEFAULT 1,
QNAINDENT NUMBER(3) DEFAULT 0,
MEMBERID VARCHAR2(30) REFERENCES MEMBER(MEMBERID),
ADMINID VARCHAR2(30) REFERENCES ADMIN(ADMINID)
);

SELECT * FROM QNA;

DROP SEQUENCE QNA_SEQ;
CREATE SEQUENCE QNA_SEQ  NOCYCLE NOCACHE;
