-- SQL 넣는곳


--글쓰기.
INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'정지회원 해제하려면','정지된 회원을 해제하려면 어떻게 해야하나요','10.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

SELECT * FROM QNA;
COMMIT;
--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '정지회원 해제하려면', '가입하신 아이디 본인의 이름과 전화번호를 보내주시면 해제할 수 있습니다', '10.jpg', '0', SYSDATE, 
        '192.22.16.12', 1, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNANOPW,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'주자장 이용시간','주자장 이용시간을 알려주세요','12.jpg','0',
SYSDATE,'192.22.16.12','8282',QNA_SEQ.CURRVAL,0,0,'BBB');

COMMIT;
--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '주자장 이용시간', '주자장 이용시간입니다', '12.jpg', '0', SYSDATE, 
        '192.22.16.12', 3, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'팝콘구매','팝콘은 어디서 사나요','12dk.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');
COMMIT;
--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '팝콘구매', '팝콘은 매장이나 사이트 상단 스낵코너에서 구매가 가능합니다', '12dk.jpg', '0', SYSDATE, 
        '192.22.16.12', 5, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'영화 개봉시기','영화 개봉 시기는 어디서 알수있나요','11.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '영화 개봉시기', '영화 개봉시기는 공지사항에 보시면 알수있습니다', '11.jpg', '0', SYSDATE, 
        '192.22.16.12', 7, 0+1, 0+1, 'admin');
        
 COMMIT;       

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'회원등급 올리는 방법','회원등급은 어떻게 올리나요','17.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

COMMIT;

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '회원등급 올리는 방법', '회원등급은 영화예매로 누적금액 20만원 초과시 올리실수있습니다', '17.jpg', '0', SYSDATE, 
        '192.22.16.12', 9, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'회원정보수정','회원정보를 수정하려면 어떻게 해야하나요','18.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '회원정보수정', '회원정보 수정은 MYMAC에 들어가시면 하실수있습니다', '18.jpg', '0', SYSDATE, 
        '192.22.16.12', 11, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'회원탈퇴','회원탈퇴를 수정하려면 어떻게 해야하나요', '2.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '회원탈퇴','회원탈퇴는 MYMAC에 들어가시면 하실수있습니다', '2.jpg', '0', SYSDATE, 
        '192.22.16.12', 13, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'이벤트 정보','이벤트 정보는 어디서 볼수있나요', '9.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '이벤트 정보', '이벤트 정보는 이벤트 게시판에서 확인 가능합니다', '9.jpg', '0', SYSDATE, 
        '192.22.16.12', 15, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'ID/PW 찾는법','ID/PW는 어떻게 찾나요', 'jFal.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, 'ID/PW 찾는법', 'ID/PW는 로그인 화면에서 ID/PW찾기를 통해 찾을 수 있습니다', 'jFal.jpg', '0', SYSDATE, 
        '192.22.16.12', 17, 0+1, 0+1, 'admin');

INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'영화예매','영화예매는 어디서 하나요','팝콘콤보.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '영화예매', '영화예매는 페이지 상단에 예매버튼을 통해 가능합니다', '10.jpg', '0', SYSDATE, 
        '192.22.16.12', 19, 0+1, 0+1, 'admin');
        
INSERT INTO QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID) VALUES(
QNA_SEQ.NEXTVAL,'개인정보 찾는법','ID/PW는 어떻게 찾나요', 'jFal.jpg','0',
SYSDATE,'192.22.16.12',QNA_SEQ.CURRVAL,0,0,'AAA');

--답변글쓰기
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNAGROUP,QNASTEP,QNAINDENT,ADMINID)
		VALUES(QNA_SEQ.NEXTVAL, '개인정보 찾는법', 'ID/PW는 로그인 화면에서 ID/PW찾기를 통해 찾을 수 있습니다', 'jFal.jpg', '0', SYSDATE, 
        '192.22.16.12', 21, 0+1, 0+1, 'admin');
COMMIT;

select * from qna;
--답변글쓰기
INSERT INTO QNA VALUES(
QNA_SEQ.NEXTVAL,'QNA제목','내용입니다','파일','0',
SYSDATE,'192.22.16.12','8282',QNA_SEQ.CURRVAL,0,0,'AAA','admin');

--리스트 최근순.
		SELECT * FROM(
		SELECT ROWNUM RN ,A.* FROM(
		SELECT Q.*,M.MEMBERNAME FROM
		QNA Q, MEMBER M	
		WHERE Q.MEMBERID=M.MEMBERID
		ORDER BY QNAGROUP DESC, QNASTEP)A)
        WHERE RN BETWEEN 1 AND 5;



-- 히트수 가장많은것 3가지 상단 출력용 리스트
	SELECT * FROM(
		SELECT ROWNUM
		RN ,A.* FROM(
		SELECT Q.*,M.MEMBERNAME
		FROM QNA Q, MEMBER M
		WHERE
		Q.MEMBERID=M.MEMBERID
		ORDER BY QNAHIT DESC)A)
		WHERE RN BETWEEN
		1 AND 3;

--글 갯수 총합
SELECT COUNT(*) FROM QNA ;

--페이징 처리 하기 
SELECT * FROM(
SELECT ROWNUM RN ,A.* FROM (
SELECT * FROM QNA ORDER BY QNANO)A)
WHERE RN BETWEEN 1 AND 5;


-- Qna 써치 기능 
SELECT * FROM(
	SELECT ROWNUM RN, A.* FROM(
	SELECT Q.*,M.MEMBERNAME FROM
		QNA Q, MEMBER M WHERE Q.MEMBERID=M.MEMBERID 
			AND ( Q.QNANO LIKE '%A%' OR
				 Q.QNATITLE LIKE '%A%' OR
				 M.MEMBERNAME LIKE '%A%' OR
				 QNAFILE LIKE '%A%'	)		 
			ORDER BY QNAGROUP DESC, QNASTEP)A)
       		 WHERE RN BETWEEN 1 AND 5;
             
--QNA 글 갯수 가져오기
	    SELECT COUNT(QNATITLE)
		FROM
		QNA Q, MEMBER M
		WHERE Q.MEMBERID=M.MEMBERID
		AND ( Q.QNANO LIKE '%A%' OR
			 Q.QNATITLE LIKE '%A%' OR
			 M.MEMBERNAME LIKE '%A%' OR
			 Q.QNAFILE LIKE '%A%' )
		ORDER BY QNAGROUP DESC, QNASTEP;


--글 수정하기.
UPDATE QNA SET QNATITLE='수정하기',
                        QNACONTENT='수정본문',
                        QNAFILE='파일수정',
                        QNADATE=SYSDATE,
                        QNAIP='121-15-89-66',
                        QNANOPW='비번'
                        WHERE QNANO=6 AND MEMBERID='AAA';
-- 답변글쓰기. 스텝설정
	UPDATE QNA SET
		QNASTEP =
		QNASTEP+1
		WHERE QNAGROUP = QNAGROUP AND QNASTEP>QNASTEP;

--답변글쓰기.
INSERT INTO
		QNA(QNANO,
		QNATITLE, QNACONTENT, QNAFILE, QNAHIT, QNADATE,
		QNAIP,QNANOPW,QNAGROUP,QNASTEP,QNAINDENT,MEMBERID)
		VALUES(
		QNA_SEQ.NEXTVAL,
		QNATITLE,
		QNACONTENT,
		QNAFILE,
		QNAHIT,
		SYSDATE,
		QNAIP,
		QNANOPW,
		QNAGROUP,
		QNASTEP+1,
		QNAINDENT+1,
		MEMBERID)



--글 본 문 보기  / / 히트업추가시키기.
SELECT * FROM QNA WHERE QNANO=6;

--히트업
UPDATE QNA SET QNAHIT= QNAHIT+1 WHERE QNANO=14;


--글삭제
DELETE FROM QNA WHERE QNANO=10 AND MEMBERID='AAA';



--이전글 
SELECT * FROM QNA WHERE QNANO=(SELECT max(QNANO) FROM QNA WHERE QNANO<42);

--다음글
                
SELECT * FROM QNA WHERE QNANO=(SELECT min(QNANO) FROM QNA WHERE QNANO>42);

commit;



SELECT * FROM QNA;